(()=>{'use strict';
const api=String(window.WAR_PROJECT_API_URL||'').replace(/\/$/,'');
const key='war-project-session';
const token=()=>sessionStorage.getItem(key)||localStorage.getItem(key)||'';
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const request=async(path,options={})=>{const response=await fetch(api+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Ошибка сервера.');return data};
let players=[];
const setPlayers=next=>{players=Array.isArray(next)?next:[];$$('[data-player-list]').forEach(box=>box.textContent=players.length?players.join(', '):'Сейчас никого нет.');$$('[data-player-select]').forEach(select=>{const selected=select.value;select.replaceChildren();if(!players.length){const option=new Option('НЕТ ИГРОКОВ ОНЛАЙН','');option.disabled=true;option.selected=true;select.add(option);select.disabled=true;return;}select.disabled=false;players.forEach(name=>select.add(new Option(name,name,false,name===selected||(!selected&&name===players[0]))));});};
const updateStatus=async()=>{try{const data=await request('/admin/status');$('#adminDenied').hidden=true;$('#adminPanel').hidden=false;$$('[data-bridge-state]').forEach(node=>node.textContent=data.online?'МОСТ ПОДКЛЮЧЁН':'МОСТ НЕ ЗАПУЩЕН');$$('.admin-status').forEach(node=>node.classList.toggle('online',!!data.online));$$('[data-player-count]').forEach(node=>node.textContent=data.players.length+' / '+(data.maxPlayers||'—')+' ИГРОКОВ');setPlayers(data.players);}catch(error){$('#adminDenied').hidden=false;$('#adminPanel').hidden=true;}};
const execute=async(form,body)=>{const output=$('.command-result',form),button=$('button[type="submit"]',form);button.disabled=true;output.className='command-result';output.textContent='Команда отправлена…';try{const command=await request('/admin/commands',{method:'POST',body:JSON.stringify(body)});for(let attempt=0;attempt<15;attempt++){await new Promise(resolve=>setTimeout(resolve,1000));const state=await request('/admin/commands/'+command.id);if(state.status==='completed'){output.classList.add('ok');output.textContent=state.result||'Команда выполнена.';await updateStatus();return;}}output.textContent='Команда в очереди.';}catch(error){output.classList.add('error');output.textContent=error.message||'Не удалось выполнить команду.';}finally{button.disabled=false;}};
const grantCoins=async form=>{const output=$('.command-result',form),button=$('button[type="submit"]',form),values=Object.fromEntries(new FormData(form).entries()),amount=Number(values.amount);button.disabled=true;output.className='command-result';if(!values.account||!Number.isInteger(amount)||amount===0){output.classList.add('error');output.textContent='Введи ник и целую сумму.';button.disabled=false;return;}output.textContent='Команда отправляется…';try{const message=`WP COINS: ${amount>0?'+':''}${amount} для ${values.account}. ${values.reason||''}`.trim();await request('/admin/commands',{method:'POST',body:JSON.stringify({action:'say',message})});output.classList.add('ok');output.textContent='Команда отправлена в очередь сервера.';form.reset();}catch(error){output.classList.add('error');output.textContent=error.message||'Не удалось отправить команду.';}finally{button.disabled=false;}};
$('form[data-command]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const action=form.dataset.command;const values=Object.fromEntries(new FormData(form).entries());if(action!=='pardonAccount'&&action!=='say'&&!values.nickname)return;execute(form,{action,nickname:values.nickname||'Server',reason:values.reason||'',role:values.role||'',tag:values.tag||'',accountId:values.accountId||'',message:values.message||''});}));
$$('form[data-wallet-grant]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();grantCoins(form);}));
updateStatus();setInterval(updateStatus,10000);
})();


