(() => {
  const packs={
    ru:{code:'RU',nav_home:'Штаб',nav_privileges:'Привилегии',nav_support:'Поддержка',eyebrow:'Операция · War Project',hero_title:'Твой сервер.',hero_accent:'Твои правила.',hero_copy:'Портал War Project объединяет лаунчер, игровой аккаунт, поддержку и привилегии.',download:'Скачать лаунчер →',server:'Сервер',server_copy:'Адрес сервера появится после настройки. Лаунчер использует Forge 1.20.1.',privileges:'Привилегии',privileges_copy:'Выбери уровень поддержки. Условия выдачи подтверждает администрация сервера.',select:'Выбрать',open_support:'Открыть поддержку →',login:'Войти',register:'Создать аккаунт',nickname:'Игровой ник',password:'Пароль',confirm_password:'Повтори пароль',account_copy:'Один аккаунт для лаунчера, сайта и поддержки. Пароль передаётся только на сервер аккаунтов по защищённому соединению.'},
    uk:{code:'UA',nav_home:'Штаб',nav_privileges:'Привілеї',nav_support:'Підтримка',eyebrow:'Операція · War Project',hero_title:'Твій сервер.',hero_accent:'Твої правила.',hero_copy:'Портал War Project об’єднує лаунчер, ігровий акаунт, підтримку та привілеї.',download:'Завантажити лаунчер →',server:'Сервер',server_copy:'Адреса сервера з’явиться після налаштування. Лаунчер використовує Forge 1.20.1.',privileges:'Привілеї',privileges_copy:'Обери рівень підтримки. Умови видачі підтверджує адміністрація сервера.',select:'Обрати',open_support:'Відкрити підтримку →',login:'Увійти',register:'Створити акаунт',nickname:'Ігровий нік',password:'Пароль',confirm_password:'Повтори пароль',account_copy:'Один акаунт для лаунчера, сайту й підтримки. Пароль передається лише на сервер акаунтів через захищене з’єднання.'},
    en:{code:'EN',nav_home:'Base',nav_privileges:'Privileges',nav_support:'Support',eyebrow:'Operation · War Project',hero_title:'Your server.',hero_accent:'Your rules.',hero_copy:'War Project brings together the launcher, game account, support, and privileges.',download:'Download launcher →',server:'Server',server_copy:'The server address will appear after setup. The launcher uses Forge 1.20.1.',privileges:'Privileges',privileges_copy:'Choose a support level. Server administration confirms fulfilment terms.',select:'Select',open_support:'Open support →',login:'Sign in',register:'Create account',nickname:'Game nickname',password:'Password',confirm_password:'Repeat password',account_copy:'One account for the launcher, website, and support. Your password is sent only to the account server over a secure connection.'}
  };
  const text=(el,value)=>{if(el&&value!==undefined)el.textContent=value};
  const content={
    ru:{cards:[['01 / Лаунчер','Готов к игре','Моды, Java и настройки производительности управляются в приложении War Project.','Windows 10 / 11'],['02 / Аккаунт','War Project ID','Один игровой аккаунт для сайта, лаунчера и обращений в поддержку.','Открыть аккаунт →'],['03 / Поддержка','Без очередей','Подай запрос на пересмотр наказания в отдельном окне.','Открыть поддержку →']],tiers:[['Уровень 01','Боец','Базовая поддержка проекта и роль участника War Project.'],['Уровень 02','Разведчик','Отличительный префикс и доступ к закрытым новостям.'],['Уровень 03','Завоеватель','Префикс [ЗАВ] и приоритетный вход.'],['Уровень 04','Командир','Уникальный цвет имени и расширенная косметика.'],['Уровень 05','Генерал','Максимальный уровень поддержки и особый статус.']],actions:[['Снять наказание','Бан','Заявка на пересмотр блокировки игрового аккаунта.'],['Снять наказание','Мут','Запрос на досрочное снятие запрета общения.'],['Снять наказание','Варны','Заявка на пересмотр предупреждений аккаунта.']],open:'Открыть окно →',footer:'War Project × Field Systems',discord:'Discord сообщества ↗',client:'Клиент 0.1.0'},
    uk:{cards:[['01 / Лаунчер','Готово до гри','Моди, Java і налаштування продуктивності керуються у застосунку War Project.','Windows 10 / 11'],['02 / Акаунт','War Project ID','Один ігровий акаунт для сайту, лаунчера й звернень у підтримку.','Відкрити акаунт →'],['03 / Підтримка','Без черг','Подай запит на перегляд покарання в окремому вікні.','Відкрити підтримку →']],tiers:[['Рівень 01','Боєць','Базова підтримка проєкту та роль учасника War Project.'],['Рівень 02','Розвідник','Особливий префікс і доступ до закритих новин.'],['Рівень 03','Завойовник','Префікс [ЗАВ] і пріоритетний вхід.'],['Рівень 04','Командир','Унікальний колір імені та розширена косметика.'],['Рівень 05','Генерал','Максимальний рівень підтримки й особливий статус.']],actions:[['Зняти покарання','Бан','Заявка на перегляд блокування ігрового акаунта.'],['Зняти покарання','Мут','Запит на дострокове зняття заборони спілкування.'],['Зняти покарання','Варни','Заявка на перегляд попереджень акаунта.']],open:'Відкрити вікно →',footer:'War Project × Field Systems',discord:'Спільнота Discord ↗',client:'Клієнт 0.1.0'},
    en:{cards:[['01 / Launcher','Ready to play','Mods, Java, and performance settings are managed in the War Project app.','Windows 10 / 11'],['02 / Account','War Project ID','One game account for the website, launcher, and support requests.','Open account →'],['03 / Support','No queues','Submit a punishment review request in a separate window.','Open support →']],tiers:[['Level 01','Fighter','Basic project support and a War Project member role.'],['Level 02','Scout','A distinctive prefix and access to private news.'],['Level 03','Conqueror','[CON] prefix and priority login.'],['Level 04','Commander','A unique name colour and extended cosmetics.'],['Level 05','General','Maximum support level and a special status.']],actions:[['Punishment review','Ban','Request a review of a game account suspension.'],['Punishment review','Mute','Request an early review of a chat restriction.'],['Punishment review','Warnings','Request a review of account warnings.']],open:'Open window →',footer:'War Project × Field Systems',discord:'Discord community ↗',client:'Client 0.1.0'}
  };
  const flags={ru:'ru',uk:'uk',en:'en'};
  const apply=(lang)=>{const p=packs[lang]||packs.ru,d=content[lang]||content.ru;document.documentElement.lang=lang;localStorage.setItem('war-project-language',lang);document.querySelectorAll('[data-i18n]').forEach(el=>text(el,p[el.dataset.i18n]));const f=document.querySelector('#languageFlag');if(f){f.dataset.lang=flags[lang];f.innerHTML='<span class="flag-icon" data-lang="'+flags[lang]+'"></span>'}text(document.querySelector('#languageCode'),p.code);document.querySelectorAll('.grid3').forEach((grid,group)=>{const rows=group===0?d.cards:d.actions;grid.querySelectorAll('.card').forEach((card,i)=>{const row=rows[i];if(!row)return;text(card.querySelector('.eyebrow'),row[0]);text(card.querySelector('h3'),row[1]);text(card.querySelector('p'),row[2]);if(group===0)text(card.querySelector('.tag'),row[3]);else text(card.querySelector('.button'),d.open)})});document.querySelectorAll('.tier').forEach((tier,i)=>{const row=d.tiers[i];if(!row)return;text(tier.querySelector('.rank'),row[0]);text(tier.querySelector('h3'),row[1]);text(tier.querySelector('p'),row[2]);text(tier.querySelector('.button'),p.select)});const foot=document.querySelector('footer');if(foot){text(foot.children[0],d.footer);text(foot.children[1],d.discord);text(foot.children[2],d.client)};document.querySelectorAll('#languageMenu button').forEach(btn=>{const l=btn.dataset.lang;btn.innerHTML='<span class="flag-icon" data-lang="'+l+'"></span>'+({ru:'Русский',uk:'Українська',en:'English'}[l])});document.querySelector('#languageMenu').hidden=true;};
  document.querySelector('#languageToggle')?.addEventListener('click',()=>{const m=document.querySelector('#languageMenu');m.hidden=!m.hidden});document.querySelectorAll('#languageMenu button').forEach(btn=>btn.addEventListener('click',()=>apply(btn.dataset.lang)));apply(localStorage.getItem('war-project-language')||'ru');
})();


\n(()=>{const l=localStorage.getItem('war-project-language')||'ru',d={ru:{account:'Аккаунт',status:'Состояние связи'},uk:{account:'Акаунт',status:'Стан зв’язку'},en:{account:'Account',status:'Connection status'}}[l]||{};const a=document.querySelector('.account-link');if(a&&a.childNodes[1])a.childNodes[1].nodeValue=d.account;const s=document.querySelector('.hero-note .eyebrow');if(s)s.textContent=d.status;})();
