(() => {
  const packs = {
    ru: { flag:'🇷🇺', code:'RU', nav_home:'Штаб', nav_privileges:'Привилегии', nav_support:'Поддержка', eyebrow:'Операция · War Project', hero_title:'Твой сервер.', hero_accent:'Твои правила.', hero_copy:'Портал War Project объединяет лаунчер, игровой аккаунт, поддержку и привилегии.', download:'Скачать лаунчер →', server:'Сервер', server_copy:'Адрес сервера появится после настройки. Лаунчер использует Forge 1.20.1.', privileges:'Привилегии', privileges_copy:'Выбери уровень поддержки. Условия выдачи подтверждает администрация сервера.', select:'Выбрать', open_support:'Открыть поддержку →', account_copy:'Один аккаунт для лаунчера, сайта и поддержки. Пароль передаётся только на сервер аккаунтов по защищённому соединению.', login:'Войти', register:'Создать аккаунт', nickname:'Игровой ник', password:'Пароль', confirm_password:'Повтори пароль' },
    uk: { flag:'🇺🇦', code:'UA', nav_home:'Штаб', nav_privileges:'Привілеї', nav_support:'Підтримка', eyebrow:'Операція · War Project', hero_title:'Твій сервер.', hero_accent:'Твої правила.', hero_copy:'Портал War Project об’єднує лаунчер, ігровий акаунт, підтримку та привілеї.', download:'Завантажити лаунчер →', server:'Сервер', server_copy:'Адреса сервера з’явиться після налаштування. Лаунчер використовує Forge 1.20.1.', privileges:'Привілеї', privileges_copy:'Обери рівень підтримки. Умови видачі підтверджує адміністрація сервера.', select:'Обрати', open_support:'Відкрити підтримку →', account_copy:'Один акаунт для лаунчера, сайту та підтримки. Пароль передається тільки серверу акаунтів захищеним з’єднанням.', login:'Увійти', register:'Створити акаунт', nickname:'Ігровий нік', password:'Пароль', confirm_password:'Повтори пароль' },
    en: { flag:'🇬🇧', code:'EN', nav_home:'Base', nav_privileges:'Privileges', nav_support:'Support', eyebrow:'Operation · War Project', hero_title:'Your server.', hero_accent:'Your rules.', hero_copy:'War Project brings together the launcher, game account, support, and privileges.', download:'Download launcher →', server:'Server', server_copy:'The server address will appear after setup. The launcher uses Forge 1.20.1.', privileges:'Privileges', privileges_copy:'Choose a support level. Server administration confirms fulfillment terms.', select:'Select', open_support:'Open support →', account_copy:'One account for the launcher, website, and support. Your password is only sent to the account server over a secure connection.', login:'Sign in', register:'Create account', nickname:'Game nickname', password:'Password', confirm_password:'Repeat password' }
  };
  const apply = lang => { const data = packs[lang] || packs.ru; document.documentElement.lang = lang; localStorage.setItem('war-project-language', lang); document.querySelectorAll('[data-i18n]').forEach(el => { if (data[el.dataset.i18n]) el.textContent = data[el.dataset.i18n]; }); document.querySelector('#languageFlag').textContent = data.flag; document.querySelector('#languageCode').textContent = data.code; document.querySelector('#languageMenu').hidden = true; };
  const saved = localStorage.getItem('war-project-language') || 'ru';
  document.querySelector('#languageToggle').addEventListener('click', () => { const menu = document.querySelector('#languageMenu'); menu.hidden = !menu.hidden; });
  document.querySelectorAll('[data-lang]').forEach(button => button.addEventListener('click', () => apply(button.dataset.lang)));
  document.addEventListener('click', event => { if (!event.target.closest('.language-picker')) document.querySelector('#languageMenu').hidden = true; });
  apply(saved);
})();
